update creation calls with phone numbers to account for the new format
mes-amis/docs.monami.io pull request #22
Opened 2024-12-26 09:51 UTC by gustavodiel

Hey team!

This PR updates the creation calls that have phone numbers to the new format.
Also, it removes some duplicate responses

2024-12-26 16:44 UTC, sromano reviewed
It seems we are missing the phone_numbers for the _Person Parameters_ at the _Payload Parameters_ in some places

Also, in the query parameters of _List Clients_ it says phone_number but it's not clear what the format should be for that

2024-12-31 04:30 UTC, labe commented on source/includes/_volunteers.md
> -        ],
why are phone numbers being removed from the response objects in this file?

2024-12-31 04:32 UTC, labe commented on source/includes/_clients.md
> +| phone_number   |      | Filters by any of the user's phone numbers, ex: `+15044791643` |
as a future cleanup, we should probably list at least a few of the different acceptable formats for phone numbers and birthdates

2024-12-31 04:33 UTC, labe commented on source/includes/_clients.md
> +| phone_number   |      | Filters by any of the user's phone numbers, ex: `+15044791643` |
```suggestion
| phone_number   |      | Filters by any of the user's phone numbers, e.g. `+15044791643` |
```

2024-12-31 04:33 UTC, labe commented on source/includes/_clients.md
> +| date_of_birth  | Client's birthdate eg.: `YYYY-MM-DD`
```suggestion
| date_of_birth  | Client's birthdate, e.g. `YYYY-MM-DD`                                                                                                                                                                    |
```

2024-12-31 04:34 UTC, labe commented on source/includes/_clients.md
> +| phone_numbers  | Array of Phone Numbers parameters
```suggestion
| phone_numbers  | Array of Phone Number parameters                                                                                                                                                                                 |
```

2024-12-31 04:35 UTC, labe commented on source/includes/_clients.md
> +| primary   | Is the phone number primary?                                         |
```suggestion
| primary   | Options: `true` or `false`                                        |
```

2024-12-31 04:36 UTC, labe commented on source/includes/_clients.md
> +| label     | Label or Type of phone number. Options are: `cell`, `home` or `work` |
```suggestion
| label     | Type of phone number. Options: `cell`, `home` or `work` |
```

2024-12-31 04:38 UTC, labe commented on source/includes/_clients.md
> +| number    | Phone Number's number. ex: +17075518391                              |
```suggestion
| number    | Phone number including area code, e.g. '+17075518391'                              |
```

2024-12-31 04:39 UTC, labe commented on source/includes/_clients.md
> +| phone_numbers  | Array of Phone Numbers
```suggestion
| phone_numbers  | Array of Phone Number parameters                                                                                                                                                                                  |
```

2024-12-31 04:40 UTC, labe commented on source/includes/_clients.md
> +| label     | Label or Type of phone number. Options are: `cell`, `home` or `work` |
please mirror requested changes above, or whatever that copy ends up being

2024-12-31 04:41 UTC, labe commented on source/includes/_clients.md
> +| date_of_birth  |      | Filters by the user's date of birth. Format: `mm/dd/yyyy`      |
for now, just to stay consistent with the format you've used elsewhere in this pr:

```suggestion
| date_of_birth  |      | Filters by the user's date of birth. Format: `YYYY-MM-DD`      |
```

2024-12-31 04:43 UTC, labe requested changes
some small suggested changes for copy consistency (and one medium question), otherwise looks good!

2024-12-31 14:28 UTC, gustavodiel commented on source/includes/_volunteers.md
> -        ],
They are a duplicated a couple lines bellow https://github.com/mes-amis/docs.monami.io/pull/22/files#diff-648373cd94943814ac34062621b3906278c795b6eaabb34616b3bd27ae5b7e41R57

2025-01-02 16:56 UTC, labe approved these changes
:shipit: 🎉

2025-01-02 17:30 UTC, merged